### PR TITLE
Week 3 homework Shell Scripting

### PR DESCRIPTION
**Pull request by nikola-milovanovic**
Added scripts from Linux Command Line and Shell Scripting Bible, 3rd Edition Chapter 13, Chapter 14, Chapter 15, and Chapter 16.

### CODE REVIEW

**Review by borisbradic — CHANGES_REQUESTED** [review]
Please remove files which we don't need, like outputs of scripts.

**Comment by nikola-milovanovic** [comment]
@borisbradic  PR updated.

**Review by borisbradic — CHANGES_REQUESTED** [review]
There are still some files which are not scripts, so please check again. Thank you.

**Comment by nikola-milovanovic** [comment]
I left files that scripts read from at first, I was thinking from first comment that we need to remove only output files not the ones that scripts read from. Removed them now also. Thank you.

**Review by borisbradic — APPROVED** [review]

**Pull request merged**
